version: '3'
services:
  web:
    build:
      context: . # Working dir
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Don't reference
      - .:/app # Reference the rest
  tests:
    build:
      context: . # Working dir
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # Don't reference
      - .:/app # Reference the rest
    command: ["npm", "run", "test"]